THRESHOLDS = {
    "PRICE_SPIKE_PERCENT": 3.0,
    "VOLUME_SPIKE_MULTIPLIER": 2.0,
    "VOLATILITY_THRESHOLD": 2.5,
    "SHORT_MOVING_AVERAGE": 5,
    "LONG_MOVING_AVERAGE": 20
}

MONITORED_STOCKS = [
    "RELIANCE.NS",
    "TCS.NS",
    "INFY.NS",
    "AAPL",
    "TSLA"
]